quarkus.datasource.db-kind=mssql
quarkus.datasource.username=sa
quarkus.datasource.password=!Hospital0?
quarkus.datasource.jdbc.url=jdbc:sqlserver://172.19.224.1:1433;database=School;encrypt=true;trustServerCertificate=true
quarkus.http.cors.enabled=true
quarkus.http.cors.origins=localhost:3000
quarkus.http.cors.methods=*
quarkus.http.cors.access-control-allow-credentials=true