# File: src/main/resources/application.properties

quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${QUARKUS_DATASOURCE_USERNAME:user}
quarkus.datasource.password=${QUARKUS_DATASOURCE_PASSWORD:password}
quarkus.datasource.jdbc.url=${QUARKUS_DATASOURCE_URL:jdbc:postgresql://db:5432/hellodb}

quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=true