quarkus.redis.hosts=redis://redis-17689.c339.eu-west-3-1.ec2.redns.redis-cloud.com:17689
quarkus.redis.password=IHUI2jHEgVv7KdE8cwQk2MbwLYbbO2fU

openweather.api.key=4744aba22d72e853cba696777374827e


